services:
  - type: web
    name: nest-backend
    env: node
    plan: free
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://eng-soft-front-finalizado.vercel.app/
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
