services:
  - type: web
    name: nest-backend
    env: node
    plan: free
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
